.vault_template:
  stage: vault
  image: gitlab.udevs.io:5050/docker/docker:dind
  id_tokens:
    VAULT_ID_TOKEN:
      aud: gitlab.udevs.io
  before_script:
    - docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD
  script:
    - cd $CI_PROJECT_NAME
    - export VAULT_TOKEN="$(vault write -field=token $VAULT_AUTH_PATH role=$VAULT_AUTH_ROLE jwt=$VAULT_ID_TOKEN)"
    - SECRET=$(vault kv get -format=json $SECRET_PATH)
    - echo "$SECRET" | jq -r '.data.data | to_entries | .[] | "\(.key)=\(.value)"' > .env
  artifacts:
    paths:
      - $CI_PROJECT_NAME/.env
    




